version: '3.8'

services:
  api:
    container_name: setlisty-backend
    image: setlisty-api-dev:1.0.0
    build:
      context: .
      dockerfile: .Dockerfile.dev
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - backend-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    env_file:
      - .env.dev
  database:
    container_name: pgsql-setlisty
    image: postgres:10.5
    restart: always
    env_file:
      - .env.dev
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5438:5432'
    depends_on:
      - api
networks:
  backend-network:
